name: revmo
description: Sellers version of Revmo App.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter  
  intl: ^0.17.0

  cupertino_icons: ^1.0.2

  flutter_svg: ^0.21.0
  path_provider: ^2.0.6
  http: ^0.13.4
  page_transition: ^2.0.4
  form_validator: ^1.0.1
  device_info_plus: ^3.1.1
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  provider: ^6.0.1
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  loading_indicator: ^3.0.2
  get_it: ^7.2.0
  multi_select_flutter: ^4.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_rating_bar: ^4.0.0
  animate_do: ^2.0.0
  flutter_easyloading: ^3.0.3
  lottie: ^1.2.1
  dio: ^4.0.6
  syncfusion_flutter_sliders: ^20.1.59
  filter_list: ^1.0.1
  flutter_multi_select_items: ^0.4.0
  persistent_bottom_nav_bar: ^4.0.2
  pmvvm: ^2.3.0
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  currency_text_input_formatter: ^2.1.8
  iconsax: ^0.0.8
  expandable_page_view: ^1.0.17





dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/blueLogo.png
    - assets/images/splash.png
    - assets/images/sign_in_bg.png
    - assets/images/congratz.png
    - assets/icons/
    - assets/images/

  fonts:
      - family: Eurostile
        fonts:
          - asset: assets/fonts/Eurostile.ttf
      - family: Gibson
        fonts:
          - asset: assets/fonts/Gibson-Regular.otf
          - asset: assets/fonts/Gibson-Italic.otf
            style: italic
          - asset: assets/fonts/Gibson-SemiBold.otf
            weight: 500
          - asset: assets/fonts/Gibson-SemiBoldIt.otf
            weight: 500
            style: italic
          - asset: assets/fonts/Gibson-Bold.otf
            weight: 700
          - asset: assets/fonts/Gibson-BoldItalic.otf
            weight: 700
            style: italic
      - family: Gibson_Light
        fonts:
          - asset: assets/fonts/Gibson-Light.otf
          - asset: assets/fonts/Gibson-LightIt.otf
            style: italic
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto.ttf

